#
2
# This is free software, lisence use MIT.
3
# 
4
# Copyright (C) 2019 P3TERX <https://p3terx.com>
5
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
6
# 
7
# <https://github.com/KFERMercer/OpenWrt-CI>
8
#
9
​
10
name: OpenWrt-CI
11
​
12
on:
13
  push:
14
    branches: 
15
      - CI-demo
16
  #     ↑↑↑ 改成你的分支名, 一般是master
17
  # schedule:
18
  #   - cron: 0 20 * * *
19
  # release:
20
  #   types: [published]
21
​
22
jobs:
23
  build:
24
    runs-on: ubuntu-latest
25
​
26
    steps:
